services:

  postgres-db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  frontend:
    build:
      context: ./frontend
      args:
        - API_BACKEND_URL=http://localhost:8080
    ports:
      - 5173:80
