# Setup an action to run the backend CI for PRs

# name of the action
name: Backend CI

# when should it run
on:
  pull_request:
    branches:
      - main

# what should it do
jobs:
  # name of the job
  build:
    # what should it run on
    runs-on: ubuntu-latest
    # default values for all the steps
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'maven'
      - name: Run Maven build
        run: mvn install -DskipTests
      - name: Run tests
        run: mvn test